spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console  # You can access the H2 console at http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates/updates the database schema
    show-sql: false      # Show SQL queries in the log
    database-platform: org.hibernate.dialect.H2Dialect